# basic training options
batch_size: 32
iter: 150
val_iter: 1
save_iter: 1

# main fixed options
dataset_name: q1
model_name: simple_net
device: cuda

# dataset optionss
input_length: 1200

# optimizer args
optimizer:
  name: AdamP
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.000001
  nesterov: True
schedule:
  name: ReduceLROnPlateau
  factor: 0.2
  patience: 5