# basic training options
batch_size: 16
iter: 501
val_iter: 10
save_iter: 50

# main fixed options
dataset_name: q2
model_name: simple_net
device: cuda

# dataset options
input_length: 1200

# optimizer args
optimizer:
  name: SGD
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.000001
  nesterov: True
schedule:
  name: ReduceLROnPlateau
  factor: 0.2
  patience: 5